src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days between service or inspection</description>
        <inlineHelpText>Number of days between service or inspection</inlineHelpText>
        <label>Maintenance Cycle Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Due__c</fullName>
        <label>Date Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Reported__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No equipment by that name exists</errorMessage>
            <filterItems>
                <field>Equipment__c.Replacement_Part__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>Search for the equipment for this work order.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Routine Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End of Life</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <label>Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WorkOrderHelper.cls
public class WorkOrderHelper {

    public static boolean isFirstRun = true; 
    private static Date dateToday = System.today();

    public static void updateWorkOrders(List<Work_Order__c> workOrders, Map<Id,Work_Order__c> oldWorkOrdersMap, boolean isBefore){
        isFirstRun = false;

        if (isBefore){

            //do nothing
            System.debug('isBefore');

        } else {

            System.debug('isAfter');

            List<Work_Order__c> nextMaintenanceList = new List<Work_Order__c>();
        
            for (Work_Order__c order : [SELECT Id, Account__c, Equipment__c, Status__c, Type__c, Account__r.Name, Equipment__r.Name, Equipment__r.Maintenance_Cycle__c
                                        FROM Work_Order__c
                                        WHERE Status__c = 'Closed' AND
                                              Id IN: workOrders ])
            {
                System.debug(order);
                System.debug(oldWorkOrdersMap.get(order.Id));
                if (order.Status__c != oldWorkOrdersMap.get(order.Id).Status__c){
                    System.debug('creating new order');
                    Work_Order__c newOrder = new Work_Order__c();
                    newOrder.Name = order.Account__r.Name + ' ' + order.Equipment__r.Name + ' ' + 'Maintenance';
                    newOrder.Status__c = 'Open';
                    newOrder.Type__c = 'Routine Maintenance';
                    newOrder.Equipment__c = order.Equipment__c;
                    newOrder.Account__c = order.Account__c;
                    newOrder.Date_Reported__c = dateToday;
                    newOrder.Date_Due__c = dateToday.addDays(Integer.valueOf(order.Equipment__r.Maintenance_Cycle__c));
                    nextMaintenanceList.add(newOrder);
                }
            }

            insert nextMaintenanceList;
        }


        isFirstRun = true;
    }

}